Makes positronics able to become human'ish
RepoStash/FD-NewBay pull request #62
Opened 2024-11-01 14:06 UTC by CheBuRek017

ПР делает что-то умное. Добавляет флаги на возможность выбора волос и других штук ИПСам вместе с снятием ограничений на протезы. Полу-модульно.

### Чейнджлог
```yml
🆑СруИгКул017
tweak: ИПСы теперь могут выбирать протезы веймеда и волосы.
/🆑
```

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.

2024-11-01 23:35 UTC, 800maximum123 reviewed
В целом - более ничего запрещенного. (вроде-бы)

2024-11-01 23:35 UTC, 800maximum123 commented on code/modules/mob/living/carbon/human/examine.dm
> +		msg += ", <b>[SPAN_COLOR(s_flesh_colour, "\a [species_name]!")]</b>[(user.can_use_codex() && SScodex.get_codex_entry(get_codex_value())) ?  SPAN_NOTICE(" \[<a href='?src=\ref[SScodex];show_examined
Уверен что `s_flesh_colour`, а не вызов прока у чего-то?

2024-11-02 09:25 UTC, CheBuRek017 commented on code/modules/mob/living/carbon/human/examine.dm
> +		msg += ", <b>[SPAN_COLOR(s_flesh_colour, "\a [species_name]!")]</b>[(user.can_use_codex() && SScodex.get_codex_entry(get_codex_value())) ?  SPAN_NOTICE(" \[<a href='?src=\ref[SScodex];show_examined
Посмотри выше, я вызываю прок сверху и сую его в var. Если не проходит проверка - остаётся результат прока. Если проходит - результат изменяется на шелловский

2024-11-02 09:25 UTC, CheBuRek017 commented on code/modules/mob/living/carbon/human/examine.dm
> +		msg += ", <b>[SPAN_COLOR(s_flesh_colour, "\a [species_name]!")]</b>[(user.can_use_codex() && SScodex.get_codex_entry(get_codex_value())) ?  SPAN_NOTICE(" \[<a href='?src=\ref[SScodex];show_examined
var/s_flesh_colour = species.get_flesh_colour(src)

2024-11-02 09:26 UTC, CheBuRek017 commented on code/modules/mob/living/carbon/human/examine.dm
> +		msg += ", <b>[SPAN_COLOR(s_flesh_colour, "\a [species_name]!")]</b>[(user.can_use_codex() && SScodex.get_codex_entry(get_codex_value())) ?  SPAN_NOTICE(" \[<a href='?src=\ref[SScodex];show_examined
если шелл то s_flesh_colour = "#ffc896"

2024-11-02 11:29 UTC, 800maximum123 requested changes

2024-11-02 11:29 UTC, 800maximum123 commented on code/modules/mob/living/carbon/human/examine.dm
> +		msg += ", <b>[SPAN_COLOR(s_flesh_colour, "\a [species_name]!")]</b>[(user.can_use_codex() && SScodex.get_codex_entry(get_codex_value())) ?  SPAN_NOTICE(" \[<a href='?src=\ref[SScodex];show_examined
Что-ж. Проснулся и увидел то, что не заметил. Давай пройдемся.

Ты взял в // [FD-EDIT] не совсем тот участок кода. Если конкретно - то следовало взять это, закомментив старый код (тоже содержа его в // [FD-EDIT)

2024-11-02 11:31 UTC, 800maximum123 requested changes

2024-11-02 11:31 UTC, 800maximum123 commented on code/modules/mob/living/carbon/human/examine.dm
> +		msg += ", <b>[SPAN_COLOR(s_flesh_colour, "\a [species_name]!")]</b>[(user.can_use_codex() && SScodex.get_codex_entry(get_codex_value())) ?  SPAN_NOTICE(" \[<a href='?src=\ref[SScodex];show_examined
Что-ж. Проснулся и увидел то, что не заметил. Давай пройдемся.

Ты взял в // [FD-EDIT] не совсем тот участок кода. Если конкретно - то следовало взять это, закомментив старый код (тоже содержа его в // [FD-EDIT)

UPD. Сука, бля. Гитхаб решил показать не то. Так что вскоре просто дам номера строк

2024-11-02 11:33 UTC, 800maximum123 commented
Перед игрой где-то в 16:00 - закину этот код, конечно, на Деатх оф Хоуп (потом ревертнув), однако пофиксить надо.

2024-11-02 14:06 UTC, 800maximum123 commented
Сойдет. Мерджу, после немного отредачу

2024-11-02 14:06 UTC, merged