Immersive Sounds full
RepoStash/FD-NewBay pull request #69
Opened 2024-11-28 17:57 UTC by CheBuRek017

Добавляет возможность машинерии делать цикличные звуки + пак звуков с встроенным копирайтом.

### Чейнджлог
```yml
🆑CheBuRek
wip: Фреймворк для звуков машинерии
soundadd: Звуки машинерии
/🆑
```

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.

2024-11-29 09:42 UTC, 800maximum123 requested changes
Измени документацию. Я, тем временем, запущу это у себя и проверю работу. 
Если не будет проблем - пускаем.

2024-11-29 09:42 UTC, 800maximum123 commented on mods/_fd/immersive_sounds/README.md
> +`https://github.com/RepoStash/FD-NewBay/pull/68`
Смени ПР с 68 на 69

2024-11-29 12:30 UTC, CheBuRek017 commented
@800maximum123

2024-11-30 11:31 UTC, 800maximum123 approved these changes
Ничего более критичного не вижу. 
Good work!

2024-11-30 11:33 UTC, merged

2024-11-30 11:33 UTC, 800maximum123 commented
После запуска - перенесу на остальные бранчи